spring:
  datasource:
    #url: jdbc:mysql://52.163.84.95:3306/wsy_jwxt?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8888

  #开启SQL语句打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl