spring:
  datasource:
    #url: jdbc:mysql://52.163.84.95:3306/wsy_jwxt?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redis
    jedis:
      pool:
        max-idle: 10
        max-total: 20

server:
  port: 8888
  tomcat:
    uri-encoding: utf-8

  #开启SQL语句打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
